import {BOOKING_URL, PHONE_URL, MAP_URL, SERVICES_DATA} from './data';
const Arrow=()=> <span aria-hidden="true">↗</span>;
export default function Home(){return <>
<header><a className="logo" href="#">САЛОН-ПЛЮС<span>КАЛИНИНГРАД</span></a><nav aria-label="Основная навигация"><a href="#services">УСЛУГИ</a><a href="#space">ПРОСТРАНСТВО</a><a href="#contacts">КОНТАКТЫ</a></nav><a className="button header-book" href={BOOKING_URL}>ЗАПИСАТЬСЯ <Arrow/></a><details className="mobile-menu"><summary>МЕНЮ +</summary><nav><a href="#services">УСЛУГИ</a><a href="#space">ПРОСТРАНСТВО</a><a href="#contacts">КОНТАКТЫ</a></nav></details></header>
<main><section className="hero"><div className="hero-left"><div className="meta hero-meta"><span>ПАРИКМАХЕРСКАЯ / САЛОН КРАСОТЫ</span><span>01 — 2026</span></div><h1>САЛОН<br/><span>ПЛЮС</span><b aria-hidden="true">+</b></h1><div className="hero-bottom"><p>СТРИЖКИ.<br/>УХОД.<br/>НИЧЕГО ЛИШНЕГО.</p><a className="button" href={BOOKING_URL}>ЗАПИСАТЬСЯ <Arrow/></a></div></div><figure className="hero-photo"><img src="/salon-plus/images/salon-2.jpg" alt="Интерьер Салон-Плюс: кресла у зеркал и кирпичная стена"/><figcaption><span>РОКОССОВСКОГО, 24</span><span>09:00 — 21:00 / КАЖДЫЙ ДЕНЬ</span></figcaption></figure></section>
<div className="ticker" aria-hidden="true"><div>{Array.from({length:4},(_,i)=><span key={i}>САЛОН-ПЛЮС / СТРИЖКИ / УХОД / </span>)}</div></div>
<section id="services" className="services section"><div className="section-title"><span className="meta">02 / ПРАЙС</span><h2>УСЛУГИ<br/>И ЦЕНЫ</h2><p>Начните с главного.<br/>Остальное обсудим в кресле.</p></div><div className="service-list">{SERVICES_DATA.map((s,i)=><a href={BOOKING_URL} className="service" key={s.name}><span className="service-index">0{i+1}</span><div><h3>{s.name}</h3><p>{s.note}</p><span className="service-book">ЗАПИСАТЬСЯ ↗</span></div><span className="price">{s.price}</span></a>)}<p className="price-note">Цены указаны в карточке Яндекс Карт. Точную стоимость уточняйте при записи.</p></div></section>
<section id="booking" className="booking section"><div><span className="meta">БЕЗ ЛИШНИХ ШАГОВ</span><h2>ВАШЕ ВРЕМЯ.<br/>ВАША ЗАПИСЬ.</h2></div><div className="booking-aside"><p>Позвоните — выберем услугу<br/>и удобное время.</p><a className="button light" href={BOOKING_URL}>ЗАПИСАТЬСЯ ПО ТЕЛЕФОНУ <Arrow/></a></div></section>
<a href={PHONE_URL} className="phone-strip"><span className="meta">ПРОСТО ПОЗВОНИТЕ</span><strong>+7 (963) 294-19-09</strong><span className="meta">ПОЗВОНИТЬ ↗</span></a>
<section id="space" className="space section"><div className="space-heading"><span className="meta">03 / ПРОСТРАНСТВО</span><h2>ЗНАКОМОЕ МЕСТО.<br/>НОВЫЙ ОБРАЗ.</h2><p>Стрижки для женщин и мужчин.<br/>На Рокоссовского, 24.</p></div><div className="photo-grid"><figure><img loading="lazy" src="/salon-plus/images/salon-2.jpg" alt="Кресла и зеркала в Салон-Плюс"/><figcaption>01 / ВНУТРИ САЛОНА</figcaption></figure><figure><img loading="lazy" src="/salon-plus/images/salon-1.jpg" alt="Вход в Салон-Плюс с улицы Рокоссовского"/><figcaption>02 / ВХОД С УЛИЦЫ</figcaption></figure><div className="photo-label"><span className="meta">КАЛИНИНГРАД / 2026</span><span className="plus" aria-hidden="true">+</span><span>ДОБАВЬТЕ<br/>ВРЕМЯ ДЛЯ СЕБЯ.</span></div></div></section>
<section className="reviews section"><div><span className="meta">04 / ОТЗЫВЫ</span><h2>СЛОВО<br/>ГОСТЯМ.</h2></div><div className="rating"><strong>4,3<span>/ 5</span></strong><p>10 оценок на Яндекс Картах</p><a className="text-link" href="https://yandex.ru/maps/org/salon_plyus/140936951720/reviews/" target="_blank" rel="noreferrer">ЧИТАТЬ ОТЗЫВЫ ↗</a></div></section>
<section id="contacts" className="contacts"><div className="contact-info"><span className="meta">05 / КОНТАКТЫ</span><h2>МЫ РЯДОМ.</h2><dl><dt>АДРЕС</dt><dd>Калининград,<br/>ул. Рокоссовского, 24</dd><dt>РЕЖИМ РАБОТЫ</dt><dd>Каждый день, 09:00–21:00</dd><dt>ТЕЛЕФОН</dt><dd><a href={PHONE_URL}>+7 (963) 294-19-09</a></dd></dl><a className="button" href={MAP_URL} target="_blank" rel="noreferrer">ПОСТРОИТЬ МАРШРУТ <Arrow/></a></div><div className="map"><iframe title="Салон-Плюс на Яндекс Картах" loading="lazy" src="https://yandex.ru/map-widget/v1/?mode=search&oid=140936951720&ol=biz&z=17"/><a href={MAP_URL} target="_blank" rel="noreferrer" className="map-link">ОТКРЫТЬ В ЯНДЕКС КАРТАХ ↗</a></div></section>
<section className="final section"><span className="meta">САЛОН-ПЛЮС / КАЛИНИНГРАД</span><h2>ПОРА<br/>СТРИЧЬСЯ.</h2><a className="button light" href={BOOKING_URL}>ЗАПИСАТЬСЯ <Arrow/></a></section>
</main><footer><a href="#" className="logo">САЛОН-ПЛЮС</a><span>© 2026</span><a href={MAP_URL} target="_blank" rel="noreferrer">ЯНДЕКС КАРТЫ ↗</a><details><summary>Конфиденциальность</summary><p>Сайт не содержит форм для сбора персональных данных. Для записи используется телефон. Карта и внешние ссылки открывают сервис Яндекса, где действует его политика конфиденциальности.</p></details></footer><div className="mobile-bar"><a href={BOOKING_URL}>ЗАПИСАТЬСЯ ↗</a><a href={PHONE_URL}>ПОЗВОНИТЬ ↗</a></div></>}




